---

- hosts: openstack_nodes
  gather_facts: true

  roles:
  - role: host-setup
    tags:
      - host-setup

  - role: kolla-setup
    tags:
      - kolla
    when: inventory_hostname is search('os-ctrl') or inventory_hostname is search('os-ctrl01')
