---

- hosts: all
  gather_facts: true

  roles:
  - role: host-setup
    tags:
      - host-setup

  - role: pre-setup
    tags:
      - pre-setup
    when: inventory_hostname is not search('kolla')

  - role: kolla-setup
    tags:
      - kolla
    when: inventory_hostname is search('kolla')
