---

- setup:

- debug:
    var: ansible_interfaces

- name: Run dhclient command
  shell: |
    ip link set {{item}} up
    if ! ip addr show {{item}}|egrep "^\s+inet\s[0-9]+." > /dev/null 2>&1;then
      if pgrep dhclient > /dev/null 2>&1;then
          pkill dhclient > /dev/null 2>&1
          if ! which dhclient > /dev/null 2>&1;then
            dnf install dhcp-client -y -q
            dhclient > /dev/null 2>&1
          fi
      else
        dhclient > /dev/null 2>&1
      fi
    fi
  with_items:
    - "{{ansible_interfaces}}"
  when: item is not match('lo')
  ignore_errors: true

- setup:

- name: template out resolv.conf
  template:
    src: "{{ansible_distribution}}/resolv.j2"
    dest: /etc/resolv.conf
    mode: 0644
    owner: root
    group: root
  notify: restart_network

- name: template out eth0 config
  template:
    src: "{{ansible_distribution}}/eth0.j2"
    dest: /etc/sysconfig/network-scripts/ifcfg-eth0
    mode: 0644
    owner: root
    group: root
  notify: restart_network

- name: template out eth1 config
  template:
    src: "{{ansible_distribution}}/eth1.j2"
    dest: /etc/sysconfig/network-scripts/ifcfg-eth1
    mode: 0644
    owner: root
    group: root
  when: ansible_eth1 is defined
  notify: restart_network

- name: template out eth2 config
  template:
    src: "{{ansible_distribution}}/eth2.j2"
    dest: /etc/sysconfig/network-scripts/ifcfg-eth2
    mode: 0644
    owner: root
    group: root
  when: ansible_eth2 is defined
  notify: restart_network

- name: template out eth3 config
  template:
    src: "{{ansible_distribution}}/eth3.j2"
    dest: /etc/sysconfig/network-scripts/ifcfg-eth3
    mode: 0644
    owner: root
    group: root
  when: ansible_eth3 is defined
  notify: restart_network
