---

- setup:

- debug:
    var: ansible_interfaces

- name: Run dhclient command
  shell: |
    ip link set {{item}} up
    if ! ip addr show {{item}}|egrep "^\s+inet\s[0-9]+." > /dev/null 2>&1;then
      if pgrep dhclient > /dev/null 2>&1;then
          pkill dhclient > /dev/null 2>&1
          if ! which dhclient > /dev/null 2>&1;then
            dnf install dhcp-client -y -q
            dhclient > /dev/null 2>&1
          fi
      else
        dhclient > /dev/null 2>&1
      fi
    fi
  with_items:
    - "{{ansible_interfaces}}"
  when: item is not match('lo')
  ignore_errors: true

- setup:

- name: template out network config for Ubuntu
  template:
    src: "{{ansible_distribution}}/networks.j2"
    dest: /etc/netplan/networks.yaml
    mode: 0644
    owner: root
    group: root
  notify: apply_netconfig

- name: template out resolv.conf
  template:
    src: resolv.j2
    dest: /etc/resolv.conf
    mode: 0644
    owner: root
    group: root
  notify: apply_netconfig
