---

- name: Install packages
  package:
    name:
      - git
      - vim
      - build-essential
      - python3-dev
      - libffi-dev
      - gcc 
      - libssl-dev
      - python3-pip
    state: latest

- name: Update pip
  command: pip3 install -U pip

- name: Update OS
  package:
    name: "*"
    state: latest
  notify: reboot_os
