# Target host type [kvm, baremetal, non_kvm]
# kvm: true - Set true if target machines are KVM guest
# baremetal: true - Set true if target machines are baremetal host
# non_kvm: - Set true if target hosts are VMs and hosted on other hypervisor

kvm: true
baremetal: false
non_kvm: false
# Openstack deployment type: [allinone, multinode]
all_in_one: true
multinode: false

disk: vdb
disk_path: "/dev/{{disk}}"

openstack_release: victoria

ctrl_plane_interface: eth1
data_interface: eth2

controllers:
  hostname_01: "os-ctrl"
  ip_01: 192.168.10.221

computes:
  hostname_01: "os-com01"
  ip_01: "192.168.10.207"

auth_info:
  user: root
  key_path: ~/.ssh/id_rsa
  connection: ssh

### globals.yml vars
os_services:
  aodh: yes
  ceilometer: yes
  chrony: yes
  cinder: yes
  cloudkitty: yes
  gnocchi: yes
  swift: yes

neutron:
  qos: yes
  metering: yes

openstack_tag_suffix: ""
kolla_internal_vip_address: 192.168.10.200
