---

- hosts: all
  gather_facts: true

  pre_tasks:
  - assert:
      that:
        - ansible_distribution is match('CentOS')
        - ansible_distribution_major_version == "8"
      fail_msg: "Target System must be CentOS 8"

  roles:
  - role: post-setup
    tags:
      - post-setup
    when: inventory_hostname is search('os-ctrl')
