- name: Template out br-ex interface config
  template:
    src: br-ex.j2
    mode: 0644
    dest: /etc/sysconfig/network-scripts/ifcfg-br-ex
    owner: root
    group: root

- name: Template out eth0 interface config
  template:
    src: eth0.j2
    mode: 0644
    dest: /etc/sysconfig/network-scripts/ifcfg-eth0
    owner: root
    group: root

- name: Reboot host
  reboot:
    reboot_timeout: 600
    test_command: "uptime"

- debug:
    msg:
      - "/root/keystonerc_admin contains admin creds"
      - "source this file to use openstack CLI"
      - "OpenStack Horizon url: http://{{ansible_default_ipv4.address}}/dashboard"
