- name: set hostname
  hostname:
    name: "{{inventory_hostname}}"

- name: Enable power tools
  command: dnf config-manager --enable powertools
  args:
    warn: false

- name: Install network-scripts package
  dnf:
    name: network-scripts
    state: present

- name: Stop and disable firewalld
  service:
    name: firewalld
    state: stopped
    enabled: no

- name: Stop and disable Network Manager
  service:
    name: NetworkManager
    state: stopped
    enabled: no

- name: Start and enable legacy network service
  service:
    name: network
    state: started
    enabled: yes

- name: Install openstack repo {{openstack_repo}}
  dnf:
    name: "{{openstack_repo}}"
    state: present

- name: Update OS
  dnf:
    name: "*"
    state: latest
