- name: set hostname
  hostname:
    name: "{{inventory_hostname}}.{{domain}}"
    use: systemd

- name: Add hostname entry in /etc/hosts
  lineinfile:
    path: /etc/hosts
    regexp: '^{{ansible_host}}'
    line: '{{ansible_host}} {{inventory_hostname}}.{{domain}} {{inventory_hostname}}'
    state: present

- name: Install network-scripts package
  dnf:
    name: network-scripts
    state: present

- name: Stop and disable firewalld
  service:
    name: firewalld
    state: stopped
    enabled: no

- name: Stop and disable Network Manager
  service:
    name: NetworkManager
    state: stopped
    enabled: no

- name: Start and enable legacy network service
  service:
    name: network
    state: started
    enabled: yes

- name: Start and enable rsyslog
  service:
    name: rsyslog
    state: started
    enabled: yes
