---

- name: Install Python build dependencies
  dnf:
    name:
      - python3-devel
      - libffi-devel
      - gcc
      - openssl-devel
      - python3-libselinux
      - python3-pip
    state: latest

- name: Update pip
  command: pip3 install -U pip
