---

- name: Set system host
  hostname:
    name: "{{inventory_hostname}}"
    
- name: Install rsyslog
  dnf:
    name: rsyslog
    state: latest

- name: Start rsyslog
  systemd:
    name: rsyslog
    state: started
    enabled: yes
