---

- name: reboot_os
  reboot:
    reboot_timeout: 600
    test_command: "uptime"

- name: restart_network
  service:
    name: network
    state: restarted

- name: apply_netconfig
  command: netplan --debug apply