- include_tasks: packages.yml

- name: Template out packstack answer file
  template:
    src: packstack-answers.j2
    dest: /root/packstack-answers.text
    mode: 0644
  when: inventory_hostname is search('os-ctrl')
