---

- name: Install kolla using pip (non-venv)
  command: pip install kolla-ansible

- name: Install ansible
  package:
    name: ansible
    state: latest

- name: Create dir /etc/kolla
  file:
    path: /etc/kolla
    state: directory
    owner: root
    group: root

- name: Copy globals.yml to kolla host
  copy:
    src: globals.yml
    dest: /etc/kolla/globals.yml
    mode: 0644
    owner: root
    group: root

- name: Copy password.yml in /etc/kolla
  copy:
    src: passwords.yml
    dest: /etc/kolla/
    mode: 0644
    owner: root
    group: root

- name: Generate password
  command: /usr/local/bin/kolla-genpwd

- name: Tweak ansible.conf
  lineinfile:
    path: /etc/ansible/ansible.cfg
    regexp: '^host_key_checking'
    line: 'host_key_checking=False'
    state: present
    insertafter: '^[defaults]'

- name: Tweak ansible.conf
  lineinfile:
    path: /etc/ansible/ansible.cfg
    regexp: '^pipelining'
    line: 'pipelining=True'
    state: present
    insertafter: '^[defaults]'

- name: Copy all-in-one inventory
  template:
    src: all-in-one.j2
    dest: /root/all-in-one
    mode: 0644
    owner: root
    group: root
  when: all_in_one|bool
