---

- include_tasks: root-storage.yml
  when: increase_root_space|bool

- include_tasks: vconsole.yml
  when: kvm|bool

- name: Reboot host
  reboot:
    reboot_timeout: 600
    test_command: "uptime"
  when: kvm_guest_reboot|bool
