---

- name: Install haproxy pkg
  package:
    name:
      - haproxy
      - vim
      - net-tools 
    state: latest

- name: Get seboolean for haproxy_connect_any
  shell: getsebool haproxy_connect_any|egrep "on$"
  register: get_haproxy_connect_any
  ignore_errors: true

- name: Set boolean for haproxy
  command: setsebool -P haproxy_connect_any=1
  when: get_haproxy_connect_any.rc != 0

- name: Copy haproxy logging config
  copy:
    src: 99-haproxy.conf
    dest: /etc/rsyslog.d/

- name: Create log file
  file:
    path: /var/log/haproxy.log
    state: touch

- name: restart_rsyslog
  systemd:
    name: rsyslog
    state: restarted

- name: Start haproxy
  systemd:
    name: haproxy
    state: started
