- name: Check 'net.ifnames=0 biosdevname=0' param in /etc/default/grub
  shell: cat /etc/default/grub|egrep -w ^GRUB_CMDLINE_LINUX|egrep "net.ifnames=0 biosdevname=0"
  register: _check_disable_dev_name
  ignore_errors: true

- block:
  - name: Get current GRUB_CMDLINE_LINUX settings
    shell: cat /etc/default/grub|egrep -w ^GRUB_CMDLINE_LINUX|cut -d'"' -f2
    register: _current_grub_cmd

  - debug:
      var: _current_grub_cmd.stdout_lines
  
  - name: Set fact to switch to native interface names
    set_fact:
      _new_kernel_param: "{{_current_grub_cmd.stdout + ' net.ifnames=0 biosdevname=0'}}"
    when: _current_grub_cmd.stdout_lines|length != 0

  - name: Set fact to switch to native interface names
    set_fact:
      _new_kernel_param: "net.ifnames=0 biosdevname=0"
    when: _current_grub_cmd.stdout_lines|length == 0

  - debug:
      var: _new_kernel_param

  - name: Take backup of /etc/default/grub
    copy:
      src: /etc/default/grub
      dest: /etc/default/grub-{{ansible_date_time.iso8601_basic_short}}
      mode: 0644
      owner: root
      group: root
      remote_src: yes

  - name: Update /etc/default/grub with new kernel param
    lineinfile:
      path: /etc/default/grub
      regexp: '^GRUB_CMDLINE_LINUX='
      line: 'GRUB_CMDLINE_LINUX="{{_new_kernel_param}}"'

  - name: Generate grub config for RHEL based system
    command: grub2-mkconfig -o /boot/grub2/grub.cfg
    register: _grub_generate_bios
    when: ansible_distribution is match('CentOS')

  - name: Generate grub config for Ubuntu
    command: grub-mkconfig -o /boot/grub/grub.cfg
    register: _grub_generate_bios
    when: ansible_distribution is match('Ubuntu')
   
  - name: template out eth0 config for RHEL based system
    template:
      src: "{{ansible_distribution}}/eth0.j2"
      dest: /etc/sysconfig/network-scripts/ifcfg-eth0
      mode: 0644
      owner: root
      group: root
    when: ansible_distribution is match('CentOS')

  - name: Remove old interface files for RHEL based system
    shell: ls -l /etc/sysconfig/network-scripts/ifcfg-*|egrep -v "eth|lo"|awk '{print "rm -rf "$9}'|sh
    when: ansible_distribution is match('CentOS')

  - name: Remove old interface files for Ubuntu
    shell: rm -rf /etc/netplan/*.yaml
    when: ansible_distribution is match('Ubuntu')

  - name: template out eth0 config for Ubuntu
    template:
      src: "{{ansible_distribution}}/networks-eth0.j2"
      dest: /etc/netplan/networks.yaml
      mode: 0644
      owner: root
      group: root
    when: ansible_distribution is match('Ubuntu')
  
  - name: Reboot host
    reboot:
      reboot_timeout: 600
      test_command: "uptime"
  when: _check_disable_dev_name.rc != 0
