---

- name: set hostname
  hostname:
    name: "{{inventory_hostname}}"

- include_tasks: kvm/main.yml
  when: ansible_system_vendor is match('QEMU')

- include_tasks: OS/centos/main.yml
  when: ansible_distribution is match('CentOS')
