---

- name: set hostname
  hostname:
    name: "{{inventory_hostname}}"

- include_tasks: kvm/main.yml
  when: ansible_system_vendor is match('QEMU')

- include_tasks: "{{ansible_distribution}}/main.yml"
