---

- name: Run dhclient command
  command: dhclient
  when: ansible_eth1.ipv4 is not defined

- setup:

- name: template out resolv.conf
  template:
    src: "{{ansible_distribution}}/resolv.j2"
    dest: /etc/resolv.conf
    mode: 0644
    owner: root
    group: root
  notify: restart_network

- name: template out eth0 config
  template:
    src: "{{ansible_distribution}}/eth0.j2"
    dest: /etc/sysconfig/network-scripts/ifcfg-eth0
    mode: 0644
    owner: root
    group: root
  notify: restart_network

- name: template out eth1 config
  template:
    src: "{{ansible_distribution}}/eth1.j2"
    dest: /etc/sysconfig/network-scripts/ifcfg-eth1
    mode: 0644
    owner: root
    group: root
  notify: restart_network
