- name: Install network-scripts and rsyslog package
  dnf:
    name:
      - network-scripts
      - rsyslog
    state: present

- name: Stop and disable firewalld
  service:
    name: firewalld
    state: stopped
    enabled: no

- name: Stop and disable Network Manager
  service:
    name: NetworkManager
    state: stopped
    enabled: no

- name: Start and enable legacy network service
  service:
    name: network
    state: started
    enabled: yes

- name: Start and enable rsyslog
  service:
    name: rsyslog
    state: started
    enabled: yes
