- name: Set hostname
  hostname:
    name: "{{inventory_hostname}}"

- name: Install rsyslog
  dnf:
    name: rsyslog
    state: present

- name: Start rsyslog service
  service:
    name: rsyslog
    state: started
    enabled: yes

- name: enable ipv4 forwarding in kernel
  sysctl:
    name: net.ipv4.ip_forward
    value: 1
    sysctl_set: yes
    state: present
    reload: yes
