# ips_source: "dhcp|static". Assuming the openstack server intially gets IP from dhcp.
# If the host already confiured with static IPs for eth0 and eth1, change ips_source to static
ips_source: dhcp
controller_as_compute: true
openstack_repo: centos-release-openstack-victoria
domain: quasarstack.com

# Enable(y) or Disable(n) additional projects
openstack_projects:
  manila: y
  swift: n
  ceilometer: n
  aodh: n
  panko: n
  sahara: n
  heat: n
  magnum: n
  trove: n
  ironic: n

openstack_pkgs:
  - openstack-packstack-puppet
  - openstack-nova-conductor
  - openstack-neutron
  - openstack-dashboard
  - openstack-packstack
  - openstack-nova-scheduler
  - openstack-neutron-ml2
  - openstack-nova-migration
  - openstack-glance
  - openstack-nova-common
  - openstack-selinux
  - openstack-placement-api
  - openstack-keystone
  - openstack-nova-compute
  - openstack-aodh-api
  - openstack-nova-api
  - openstack-nova-novncproxy
  - openstack-neutron-common
  - openstack-neutron-ovn-metadata-agent
  - openstack-dashboard-theme
  - openstack-aodh-evaluator
  - openstack-placement-common
  - openstack-cinder

# packstack install options
component_ssl:
  CONFIG_AMQP_ENABLE_SSL: y
  CONFIG_HORIZON_SSL: y
self_signed_ca: y


ssl_cert_input:
  CONFIG_SSL_CERT_SUBJECT_C: IN
  CONFIG_SSL_CERT_SUBJECT_ST: KA
  CONFIG_SSL_CERT_SUBJECT_L: Bangalore
  CONFIG_SSL_CERT_SUBJECT_O: QuasarStack
  CONFIG_SSL_CERT_SUBJECT_OU: CloudService
  CONFIG_SSL_CERT_SUBJECT_CN: "{{ansible_fqdn}}"
  CONFIG_SSL_CERT_SUBJECT_MAIL: "root@localhost"
